# -*- coding: utf-8 -*-
"""Parking_Space_with_yolov5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o8a9hkHYLJbo8n8tI_KD29XoeJLubiop

# developer: Mohammad mehdi Sahraei

### installing yolov5
"""

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!pip install -r requirements.txt

"""### installing kaggle and downloading dataset
- [link dataset](https://www.kaggle.com/datasets/wangwanqi/parking)
"""

!pip install kaggle

# Commented out IPython magic to ensure Python compatibility.
# %ls
#upload your json file in sample_data path

from IPython.display import Image

import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/sample_data" # path

!chmod 600 /content/sample_data/kaggle.json

!kaggle datasets download -d wangwanqi/parking

!unzip parking.zip

!mv /content/yolov5/train /content/yolov5/dataset
!mv /content/yolov5/valid /content/yolov5/dataset

"""### Training and Creating new model-(weights yolov5s.pt)
- [link yolov5](https://github.com/ultralytics/yolov5)
"""

# Commented out IPython magic to ensure Python compatibility.
# %pwd

!python train.py --img 120 --batch 16 --epochs 30 --data /content/yolov5/data/data.yaml --weights yolov5s.pt --cache #--cache showing details

"""### using trained model with yolov5"""

!cp -r /content/yolov5/runs/train/exp13 /content/drive/MyDrive

!python detect.py --source /content/sample_data/123.jpg --weights /content/drive/MyDrive/exp13/weights/last.pt --conf 0.40

Image('/content/yolov5/runs/detect/exp7/123.jpg')

"""### for showing results and graph

"""

# %load_ext tensorboard
# %tensorboard --logdir runs